language: ruby
sudo: required
cache: bundler
services: docker
before_script: mkdir debs && chmod 777 debs
script: bundle exec rake build["${ARGS}"]
jobs:
  include:
    - stage: Build aarch64
      env: ARGS="-q -a aarch64"
    - env: ARGS="-q -i -a aarch64"
    - stage: Build arm, i686, & x86_64
      env: ARGS="-q -a arm"
    - env: ARGS="-q -a i686"
    - env: ARGS="-q -a x86_64"
    - env: ARGS="-q -i -a arm"
    - env: ARGS="-q -i -a i686"
    - env: ARGS="-q -i -a x86_64"
