name: Build Node.js package

on:
  workflow_dispatch:

jobs:
  node-runtime-builder:
    runs-on: ubuntu-latest
    container:
      image: dockitava/package-builder:latest
      # this is need because... bugs?
      options: --user root
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Debug
        run: |
          mkdir -p /home/builder/
          cd /home/builder/
          ls -al
          sudo ln -s /__w/termux-packages/termux-packages | true
          ls -al /home/builder/termux-packages
      - name: Build package
        run: |
          # openssl nodejs
          cd /home/builder/termux-packages
          pwd
          hostname
          ls -al
          ./build-package.sh bc

      - name: Unpack Node.js & rename
        run: |
          mkdir -p /home/builder/termux-packages/_out/node
          cd /home/builder/termux-packages/_out
          cp -f /home/builder/termux-packages/output/bc* ./
          # TODO rename to node
          ar x ./bc_1.07.1-1_aarch64.deb data.tar.xz
          unxz -v data.tar.xz
          tar xvf data.tar
          # TODO rename bc to node
          cp -rf ./data/data/com.termux/files/usr/bin/bc ./node/libnodeexe.so
          echo == NODEOUT
          ls -al ./node

      - name: Copy Node.js runtime deps
        run: |
          mkdir -p /home/builder/termux-packages/_out/libs
          cd /home/builder/termux-packages/_out
          cp -rf /data/data/com.termux/files/usr/lib/libssl* ./libs
          cp -rf /data/data/com.termux/files/usr/lib/libcrypt* ./libs
          rm -f ./libs/*.a
          cp -f /data/data/com.termux/files/usr/lib/libc++_shared.so ./libs
          echo == NODELIBSOUT
          ls -al ./libs
          cd /home/builder/termux-packages/_out/libs
          zip -9 libs *
          ls -al

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: /home/builder/termux-packages/_out/node/libnodeexe.so
